In [1]:
1+1

2

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### define the vocabulary size
voc_size = 10000

In [6]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6342, 8288, 8231, 48],
 [6342, 8288, 8231, 527],
 [6342, 6647, 8231, 3678],
 [450, 999, 3083, 6189, 3456],
 [450, 999, 3083, 6189, 2287],
 [9992, 6342, 7837, 8231, 8631],
 [5168, 5847, 9205, 6189]]

In [7]:
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6342 8288 8231   48]
 [   0    0    0    0 6342 8288 8231  527]
 [   0    0    0    0 6342 6647 8231 3678]
 [   0    0    0  450  999 3083 6189 3456]
 [   0    0    0  450  999 3083 6189 2287]
 [   0    0    0 9992 6342 7837 8231 8631]
 [   0    0    0    0 5168 5847 9205 6189]]


In [9]:
### feature reprsentation 

dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 457ms/step


array([[[-3.48600149e-02, -3.13123465e-02, -1.88928731e-02,
          1.16815343e-02, -4.16139588e-02, -2.09581982e-02,
          3.22103016e-02,  2.71582939e-02,  1.42792724e-02,
          2.98042037e-02],
        [-3.48600149e-02, -3.13123465e-02, -1.88928731e-02,
          1.16815343e-02, -4.16139588e-02, -2.09581982e-02,
          3.22103016e-02,  2.71582939e-02,  1.42792724e-02,
          2.98042037e-02],
        [-3.48600149e-02, -3.13123465e-02, -1.88928731e-02,
          1.16815343e-02, -4.16139588e-02, -2.09581982e-02,
          3.22103016e-02,  2.71582939e-02,  1.42792724e-02,
          2.98042037e-02],
        [-3.48600149e-02, -3.13123465e-02, -1.88928731e-02,
          1.16815343e-02, -4.16139588e-02, -2.09581982e-02,
          3.22103016e-02,  2.71582939e-02,  1.42792724e-02,
          2.98042037e-02],
        [-2.03347802e-02, -2.28268635e-02, -2.76530907e-03,
         -4.50865738e-02,  3.22239436e-02, -1.67170763e-02,
          1.77862905e-02, -2.99458262e-02,  3.170676